cmd/aws.go
cmd/aws_resources.go
cmd/root.go

It lists all the supported resources from `aws`.
Also moved the logic for `preRun` and `postRun` to `aws` as it was validating that the flags `--hcl` or `--tfstate` where defined.

Added: 'resources' command to list all the supported resources from AWS

---

.gitignore
CHANGELOG.md
Dockerfile
Makefile
cmd/root.go
cmd/version.go

It adds the subcommand `version`. It fetches the version in build time (`make build` or `docker build`).
Example of the output:
```bash
~/.../github.com/cycloidio/terracognita [fg-24] $> ./terracognita version
The current version is: v0.1.5-8-g8504b09
```
The version it's basically https://git-scm.com/docs/git-describe#_examples which is:
```
v1.0.4-14-g2414721
i.e. the current head of my "parent" branch is based on v1.0.4, but since it has a few commits on top of that,
describe has added the number of additional commits ("14") and an abbreviated object name for the commit itself ("2414721") at the end.
The number of additional commits is the number of commits which would be displayed by "git log v1.0.4..parent".
The hash suffix is "-g" + unambiguous abbreviation for the tip commit of …
```

Added: Subcommand 'version'

---

CHANGELOG.md
go.mod
go.sum

The new version of `raws` includes a fix for the issue.
Closes #29

Updated: 'raws' to v1.0.1

---

.ci/pipeline.yml
.ci/variables.yml

- This PR fix the issue: `/bin/bash: golangci-lint: command not found` that we have in pipeline
- Add base context for pull request notifications

ci: add GOPATH in PATH to run binaries from PWD/go/bin and Add base context for pull request notifications

---

.gitignore
CHANGELOG.md
Makefile
aws/provider.go
cmd/aws.go
cmd/root.go
filter/filter.go
go.mod
go.sum
log/log.go
provider/import.go
provider/import_test.go
provider/resource.go
util/retry.go
writer/hcl.go
writer/state.go
writer/state_test.go

The `-verbose` uses go-kit/log to log information of what's currently happening on the import.
The `-debug` adds the `TF_LOG` so it also logs TF logs.
Closes #17

Added: '-verbose' and '-vverbose' flags

---

CHANGELOG.md
writer/format_hcl.go
writer/format_hcl_test.go
writer/hcl.go

We had some errors with keys that started with a number, those should be keeped  as `"2key"` instead of `2key`.
Closes #36

Fixed: Error on formatting HCL

---

cmd/aws.go

This way with just the logs they know whic version they are running
```
Starting Terracognita with version v0.1.6-7-gefbd33d
Importing with filters: 
Tags:    [],
Include: [aws_ses_domain_identity_verification],
Exclude: [],
Importing aws_ses_domain_identity_verification [2/2] Done!
Writing HCL Done!
Writing TFState Done!
```

cmd: Add first line of logs telling which version of terracognita is running

---

README.md

This PR fixes a local path after `go get` or cloning the repository, that caused an error if you try to follow the install steps.

README: Fix local path issue on install steps

---

go.mod
go.sum

Apache Thrift repo has moved.
Similar issues:
https://github.com/scottleedavis/mattermost-plugin-remind/issues/165
https://github.com/kubernetes/minikube/issues/5245

fix Apache thrift dependency - git repo moved

---

.ci/pipeline.yml
Makefile

We where having errors on the CI due to the way `golangci-lint` was installed, this switches it to the recomended way on the documentation.

Fix: Fix the CI errors

---

Makefile
go.sum
mock/provider.go
mock/resource.go
mock/writer.go

Only using 'goimports' and 'golint'.
It consumes to much memory and takes to much time.

Makefile: Replace golangci-lint for normal linters

---

CHANGELOG.md

With the last PR migrating to TF 0.12, we'll have a new release for it.

CHANGELOG: Bump to version 0.2

---

README.md

Before it was the logged it link which redirects users directly to the dockerhub homepage.
Closes https://github.com/cycloidio/terracognita/issues/59

README: Update the dockerhub link to be a public link to it

---

cmd/google.go
google/provider.go
google/reader.go
google/resources.go
google/resourcetype_enumer.go

In this PR: 
- custom cache for google internal resources
- three components (see below)
Following google documentation: 
HTTP(S) load balancer has 3 parts:
A backend service directs incoming traffic to an instance group. You can also use a storage bucket to serve content.
For now, I just implemented instance_group + backend_service + health_check components.
Host and path rules determine how your traffic will be directed. If you don't specify any rules, traffic will be sent to the default backend service.
Your IP address, protocol and port. This is the IP to which your client requests will come in to.
More information [here](https://cloud.google.com/load-balancing/docs/https/)

google: backend configuration for load balancing

---

google/cmd/generate.go
google/cmd/template.go
google/reader_generated.go
google/resources.go
google/resourcetype_enumer.go

In this PR: 
- four components (see below). I was not able to use the generator since there are two proxies component and the template is based on the plural of a component (Instance -> Instances but Proxy -> ProxIES). Same for Ssl and Url (not compliant with the go lint)
Following google documentation: 
HTTP(S) load balancer has 3 parts:
A backend service directs incoming traffic to an instance group. You can also use a storage bucket to serve content.
For now, I just implemented instance_group + backend_service + health_check components.
Host and path rules determine how your traffic will be directed. If you don't specify any rules, traffic will be sent to the default backend service.
target_http(s)_proxy, url_map and ssl_certificate (for https)
Your IP address, protocol and port. This …

google: intermediate configuration for load balancing

---

CHANGELOG.md
google/cmd/generate.go
google/cmd/template.go
google/reader_generated.go
google/resources.go
google/resourcetype_enumer.go

This is the final components of the HTTP(S) Google LB.
In this PR, we add two more components: `GlobalForwardingRule` and `ForwardingRule`. They are the entrypoint of the LB to redirect request to the `TargetHttp(s)Proxies`.
- `ForwardingRule` is specific to a region, this is why we slightly updated the template to take the `region` in consideration if needed.
- `GlobalForwardingRule` is the same thing but it's region-agnostic.  
More informations on this components [there](https://cloud.google.com/load-balancing/docs/forwarding-rule-concepts#https_lb)
Changelog has also been updated to add the components of #67 and #64

forwarding rule for the HTTP(S) LB

---

google/cmd/generate.go
google/cmd/template.go
google/reader.go
google/reader_generated.go
google/resources.go
google/resourcetype_enumer.go

In this PR, I added three more components for Google provider:
- `google_sql_database_instance` (SQL service)
- `google_storage_bucket` (Cloud storage)
- `google_compute_disk` (Persistent disks)
For the first time, we are using APIs different than `compute`. I slightly updated the template to handle different APIs (new field `API`).
As mentioned in this commit: https://github.com/cycloidio/terracognita/commit/c29aad5d174ce7956795a40d6ce3d02f5f86514a, you'll need to enable SQL APIs if you want to play with SQL instances.
I also added a field `NoFilter` field since `buckets` can not be filtered.

add several components

---

google/cmd/generate.go
google/cmd/template.go
google/reader.go
google/reader_generated.go
google/resources.go
google/resourcetype_enumer.go

Two new components:
- `RecordSet`: listing DNS records for a managed zone.
- `ManagedZone`: A ManagedZone is a resource that represents a DNS zone hosted by the Cloud DNS service.
The third one: `Policy`, is in beta.
`RecordSet` component is sligthly different from the others, since it needs to be feed by the `managedZones`, so this function need to be run after the `managedZones` fetching.

Google cloud DNS components

---

README.md

- `Versions` has been moved to the top and renamed to `Cloud providers` since it would be one of the first thing to see when you land on this page. 
- `Installation` has been updated with `binary` installation and `arch` installation.

readme: review on `installation` section

---

.ci/pipeline.yml

current artifacts are tagged with the wrong tag: 
```shell
$ docker run --rm cycloid/terracognita:v0.3.0 version
The current version is: v0.2.0-39-g9f5adfa
$ pacman -Qi terracognita | awk '/Version/ {print $3}'
1:0.3.0-1
$ terracognita version
The current version is: v0.2.0-39-g9f5adfa
```
tag was created with the GH release: we need to push it before generating artifacts.
I already refreshed the pipeline

ci: push tag before releasing artifacts

---

CHANGELOG.md
CONTRIBUTING.md
aws/cache.go
aws/provider.go
aws/resources.go
azurerm/cache.go
azurerm/provider.go
azurerm/resources.go
azurerm/resourcetype_enumer.go
google/provider.go
google/resources.go

Provide filters to resource functions. It will help to have more intelligence
between filtered resources.
For example 2 terraform resources can import the same element. If the 2
resources are runs, it doesn't make sense to write 2 time the same element.

Provide filters as arg to resources instead of tags only

---

CHANGELOG.md
google/cmd/generate.go
google/reader.go
google/reader_generated.go
google/resources.go
google/resourcetype_enumer.go

in this PR, we add the final CDN component ([compute backend bucket](https://www.terraform.io/docs/providers/google/r/compute_backend_bucket.html)).
IAM policies are started to be implemented. GCP handles IAM for each service:
- google_compute_iam_*
- google_storage_iam_*
- google_project_iam_*
- ...
About `ProjectCustomRole`, this one can't be generated since `Parent` needs to be set in the fluent API. If this type of request becomes redundant, we'll incorporate to the template. 
A cache needs also to be implemented since IAM import relies on the entities where IAM is applied. This cache would be embedded in the Function generation with a `IsCached` parameter to handle a seamless caching.

google: add CDN resource + IAM policies

---

CHANGELOG.md
aws/resources.go

If there is no groups we cannot import this resources so we should skip it
Closes #104

aws/resources: Befor importing 'aws_iam_user_group_membership' check grups names

---

CHANGELOG.md
aws/cmd/functions.go
aws/reader/reader.go
aws/resources.go

If the user have no group, empty group_membership is written

aws_iam_user_group_membership: do not write resource with empty group

---

CHANGELOG.md
util/retry.go
util/retry_test.go

This way the errors will be skipped and fault retries will be avoided.
This is still a hack but for the real implementation/solution we have to agree on https://github.com/cycloidio/terracognita/issues/93 so we can create an internal error type and directly assert to that type to skip errors that we know are do not need a Retry.
Close #106 close #105

util/retry: Add the 'errors' we use internally as exception

---

.github/ISSUE_TEMPLATE/new_feature.md

in order to prepare the public roadmap, we can submit this template to add a standard to the feature definition.

chore: add github template issue feature

---

CHANGELOG.md
aws/cmd/functions.go
aws/reader/reader.go
aws/resources.go
mock/resource.go
provider/resource.go

provider resource: implement SetImporter to set schema.Resource.Importer when resource is not importable.
aws resource: `aws_iam_group_membership`

aws resource: `aws_iam_group_membership` and resource.SetImporter

---

.ci/pipeline.yml

This image have been builded from upstream repo with fetch_tags
released.

ci: fix #103 use latest git resource

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go
provider/resource.go
state/writer_test.go

Fixed the logic to choose a Resource Name from the `provider.TagKey()`.`Name`. It was not working as expected and the resources where always having the random alphanumeric value instead of the other one.
Also added some more test on the part that where failing and did not have test.

Fix: Resource config name

---

CHANGELOG.md
aws/cmd/functions.go
aws/cmd/template.go
aws/cmd/template_test.go
aws/reader/reader.go
aws/resources.go
provider/import.go

Some of the paginations where not using the right "format" (most of them had the `Next*` and was not used).
Also fixed the templates to validate nil objects before trying to access and the same on the resources.

Fix: Pagination and nil pointer errors

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

this kind of interpolation (between 2 resources) leads to cyclic references at TF runtime. To avoid it, we build a list of current relations between resources then we check if a relation is already present before adding a ref to another resource

hcl: avoid mutual interpolation 

---

CHANGELOG.md
cmd/aws.go
cmd/azurerm.go
cmd/google.go
cmd/root.go
hcl/writer.go
hcl/writer_test.go
mock/writer.go
state/writer.go
state/writer_test.go
writer/options.go

```
--interpolate       Activate the interpolation for the HCL and the dependencies building for the State file (default true)
```
This option allows the user to explicitly deactivate the built-in interpolation:
- deactivate the HCL interpolation (with `${...}`)
- deactivate the State interpolation (`dependencies` #131 )

cli: add option to deactivate interpolation

---

CHANGELOG.md
go.mod
go.sum
hcl/format.go
hcl/format_test.go
hcl/writer.go
hcl/writer_test.go

In this PR, we upgrade the HCL lib to the its V2.
As expected (or not), the two libs are totally different. I first tried to take an approach "case by case" by using `reflect` on each values of the JSON config but it quickly becomes difficult / unmaintainable and you can miss some cases.
After looking around the `go-cty` lib, I found that you can extract the `cty.Type` from a raw JSON since `go-cty` relies actually on JSON. Once you have the `cty.Type`, you can easily found out the `cty.Value` and write your HCL blocks.
One thing, for the ingress/egress I found is that JSON side, we have a list:
```json
"ingress": [
{"description": "...", "from_port": 123},
{"description": "...", "from_port": 456},
]
```
so HCL side, we will ending with:
```hcl
egress      = [{ cidr_blocks = …
```

hcl/writer: upgrade HCL lib to the HCL2

---

CHANGELOG.md
aws/provider.go
errcode/codes.go
provider/import.go
provider/import_test.go

if we hit an error in the importing step and the error is not a fundamental one, we print it and we continue the import. 
```shell
$ ./terracognita aws --access-key=$AWS_ACCESS_KEY --secret-key=$AWS_SECRET_KEY -i aws_ses_active_receipt_rule_set --hcl resources.tf --tfstate resources.tfstate --region eu-west-1
Starting Terracognita with version v0.5.1-23-gb27dfef
Importing with filters:
Tags:    [],
Include: [aws_ses_active_receipt_rule_set],
Exclude: [],
Targets: [],
Importing aws_ses_active_receipt_rule_set [1/1] Done!
Writing HCL Done!
Writing TFState Done!
$ ./terracognita aws --access-key=$AWS_ACCESS_KEY --secret-key=$AWS_SECRET_KEY -i aws_ses_active_receipt_rule_set --hcl resources.tf --tfstate resources.tfstate --region eu-west-2
Starting Terracognita with version v0.5.1-23-gb27dfef …
```

provider/import: continue the import if we hit a custom error

---

.ci/pipeline.yml

default behavior is to merge, which is not the desired one. It's already on the `get` but the `put` is executed right before the test so it's the one who matter.

ci: add checkout params on pull-request resource

---

CHANGELOG.md
azurerm/cache.go
azurerm/cmd/generate.go
azurerm/cmd/template.go
azurerm/list_virtual_machine_extensions.go
azurerm/reader_generated.go
azurerm/resources.go
azurerm/resourcetype_enumer.go
go.mod
go.sum
mock/writer.go

In this PR, we add some AzureRM resources for WVD. In complement of the resources, I modified the AzureRM generation parts:
- add a new struct `ExtraArgs` to handle different types of args (only `string` was supported). First; I tried with a `map[string]string` but it's not deterministic
- add a new field to the `APIVersion` to support `preview` mode
- `tfdocs` bumped to the latest version to support VD resources
Added resources:
- VirtualDesktopHostPool
- VirtualDesktopApplicationGroup
- LogicAppActionCustom
- LogicAppWorkflow
- LogicAppTriggerCustom
- VirtualMachineExtension

azurerm: add virtual desktops resources

---

README.md

it will avoid to maintain readme for each new release

doc: udpate download to get latest release [skip ci]

---

CHANGELOG.md
go.mod
hcl/writer.go
hcl/writer_test.go
provider/resource.go

So now if they are required even if they are empty will be printed
Closes: #137

Fixed: Issues when generating HCL2

---

CHANGELOG.md
aws/provider.go
aws/reader/connector.go
cmd/aws.go

In the case of credentials generated by STS,we need to provide a `session-token` in complement of the required keys (access & secret). Before this PR, the token was set to a default empty string.
In this PR, we add a dedicated flag `--aws-session-token`. This flag can be set explicitly or it can be populated using `AWS_SESSION_TOKEN` (see [there](https://github.com/cycloidio/terracognita/issues/154#issuecomment-743351661) why).
Closes: https://github.com/cycloidio/terracognita/issues/154

aws: provide support for `AWS_SESSION_TOKEN`

---

.ci/pipeline.yml
scripts/deploy/aur.sh

a couple of elements were missing to publish on the AUR:
- ssh client to git clone
- host key checking
- git identity
result: https://aur.archlinux.org/cgit/aur.git/commit/?h=terracognita&id=b8ef1c04b36df5b1ffbe4582656d3b045cf78444
NB: pipeline has been refreshed.

[CI SKIP] release: fix AUR release

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

It was always trying to access the first element and not checking if it was empty before. Now it'll check and if it's empty it'll directly use a variable for it

hcl: Fixed issue with empty arrays and modules

---

README.md

It was too invasive for what the tool actually is and it does not provide information on how to use it
only on how it works and on the README we should have info on how to use it

README: Remove the image from the video

---

CHANGELOG.md
cmd/aws.go
cmd/google.go
errcode/codes.go
tag/tag.go
tag/tag_test.go

Also abstracted the logic to validate the Tags to the 'tag' package
with the new 'tag.New' so it can be reused

cmd: Fix error with the '--labels' flag not used on Google

---

CHANGELOG.md
aws/provider.go

And added a new one to the list 'AccessDeniedException'
To make the change on the Error handling I checked which was the error we had to fix on https://github.com/cycloidio/terracognita/issues/138 and checked the code from AWS to format errors so I knew which Code to expect.
Closes #176

aws: Changed from Message to Code check on errors

---

CHANGELOG.md
README.md
aws/provider.go
provider/resource.go

Skip RequestError raised when there is an issue on network layer.
Mainly happen when a AWS service is not available on the requested region.
+ Update readme regarding new provider.tf format
Fix #171

aws: fix #171 RequestError when service not available

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

It was required for modules to have it

Fixed: HCL prefixed module source with './'

---

CHANGELOG.md
tag/tag.go
tag/tag_test.go

Instead of jumping to the fallback first we try to clean the name of invalid characters
Closes #208

tag: Try to remove invalid characters from name

---

CHANGELOG.md
aws/resources.go

This was raising null pointer exceptions due to it
Closes #213

aws: Fixed error of accessing potential null values without validating before

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

Now if only Modules is activated, interpolation is deactivated and if it has ModuleVariables only those
specific attributes will not be interpolated so we do not end up with invalid HCL
Closes #219

hcl: Integration between Interpolation and Modules changed

---

CHANGELOG.md
tag/tag.go
tag/tag_test.go

So then we'll not have some that are less readable just because they have low case and are replaced
Closes #225

tag: Low case all the options for the resource name

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go
tag/tag.go
util/name.go
util/name_test.go

As in some cases, like 'tags', they have keys that cannot be converted directly into variables names
so we have to normalize them.
For this we reused the 'tag' logic and abstracted it to the 'util' lib so it can be shared between the 2 packages
Closes #218

hcl: When writting Module variables normalize the names

---

CHANGELOG.md
google/resources.go

We where getting 'Invalid list filter expression' errors because the 'labels' filter was not supported
with this we removed it from those resources so it works fine now

google: Fixed resources that do not suport filter by 'labels'

---

CHANGELOG.md
cmd/root.go
hcl/writer.go
hcl/writer_test.go
writer/options.go

With also the flag --hcl-provider-block which allows to opt out of the
'provider  {}' block on HCL

writer: New option HCLProviderBlock

---

CHANGELOG.md
aws/reader/connector.go

It was using a default region wich in some cases was causing issues, like in the case of 'govcloud'.
Related to #253

aws/reader: Now uses the region the user specified to initialize

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

So when we generate the varialbes for them we use the default values instead of setting them empty

hcl: Providers now use the default values for the attributes

---

CHANGELOG.md
azurerm/cache.go
azurerm/provider.go
azurerm/resources.go
cmd/azurerm.go

This is done by initializing multiple readers on the Provier PoV and then fetch resources
for each and every one of the readers
Closes #266

azurerm: Now supports multiple ResourceGroupNames

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

Before the variables had the same name and now they have a different one so they do not repeat the values
Closes #285

hcl: Fixed variables on repetitive blocks

---

CHANGELOG.md
aws/resources.go

Now we validate alll the target values not just the target itself
Closes #297

aws: Fixed issue with 'aws_lb_target_group_attachment' raising a panic

---

CHANGELOG.md
aws/cache.go
aws/cmd/functions.go
aws/reader/reader.go
aws/resources.go
aws/resourcetype_enumer.go

aws: added new resources

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go
writer/options.go

The Terraform block and provider can be specified to be written into a
dedicated key, easing the splitting of files when using the library.
This is optional and currently not made available through CLI on
purpose as the need of user/lib consumer are thought to be different.

hcl: allow writing tf/provider separate config key

---

CHANGELOG.md
azurerm/resources.go

When using deprecated azurerm_virtual_machine, we choose to define attached disk via the resource itself instead of external resource which mount disk after the boot of the VM.

azure: do not define external disk with azurerm_virtual_machine

---

CHANGELOG.md
azurerm/cache.go

As we are appending to one of the cache values we are getting potential duplication, we remove it before returning
Closes #341

azurerm: Remove duplicate values from the cache

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

A block that could be defined multiple times was never working with ModuleVariables due to the index position beeing on the key
Closes #344

hcl: Fixed issue with ModuleVariables and blocks

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go
interpolator/interpolator.go
interpolator/interpolator_test.go
mock/writer.go
provider/import.go
provider/import_test.go
state/writer.go
state/writer_test.go
writer/writer.go

This entity hides all the abstraction in terms of choosing which resource+attribute is best based on all the resources stored in it.
It'll try different ways to match the resource and the attribute and the value but the end fallback will be the one we had before, to just match any equal value to the expected value without taking into consideration the actual attribute
Closes #346

interpolator: Added new entity to deal with the interpolation logic

---

CHANGELOG.md
azurerm/provider.go

The value can't be retrieved. Terraform Azure provider set "ignored-as-imported" which is not a valid password. In this case, set the default password wich respects Azure constraints

azurerm: fix #352 admin_password

---

CHANGELOG.md
azurerm/provider.go
go.mod

It use to be all capital letters but it has to be just the first one

azurerm: Fixed the format for 'azurerm_network_security_group.security_rule.protocol'

---

CHANGELOG.md
azurerm/provider.go

For some reason this values is Empty sometime.
When importing we only list attached disk. So it should always be set to Attach

azurerm: force Attach create option with azurerm_virtual_machine_data_disk_attachment

---

CHANGELOG.md
azurerm/provider.go
interpolator/interpolator.go

We discovered that it's not just one or the other but that some are up and low, so we'll just lowcase the ID also so it'll match

Interpolator: Now the value comparision is done with locase values

---

CHANGELOG.md
hcl/writer.go
hcl/writer_test.go

And also if they are special carry on the special character '=tc=' so it can be formatted

hcl: Allow to declare module variables on map types

---

CHANGELOG.md
aws/reader/connector.go
provider/resource.go

So we do not generate wrong HCL by dismissing this configuration
Closes #340

provider/resource: Added support for 'ExactlyOneOf' schema option

---

CHANGELOG.md
aws/provider.go

aws: 'aws_alb_listener_rule' and 'aws_lb_listener_rule' with 'priority: 99999' are ignored

---

CHANGELOG.md
Makefile
aws/provider.go
azurerm/provider.go
google/provider.go
hcl/writer.go
hcl/writer_test.go
mock/provider.go
provider/provider.go
scripts/terraform-provider-update/README.md
scripts/terraform-provider-update/update.sh
vsphere/provider.go

Now each provider will have to specify to which version they are importing, this way we can later on set this version to the provider configuration on the HCL. This way we prevent compatibility issues between provider versions
Closes #378, closes #374, closes #392

provider: Added 'Version' to the Provider interface
