LICENSE, Makefile, README.md, go.mod
Update Makefile to make it more generic.
Update README and add LICENSE file for documentation purposes.
Fix issue with go.mod not having the right naming.
=> doc: update Makefile and add documentation

README.md
This commit change the "about cycloid" section to go a bit deeper about what Cycloid provide and how we are using Terracognita internally.
=> readme: Fix the about cycloid section

README.md
I assume that what was intended is to provide a link with a title.
=> Fixed: Link on the README

README.md, aws/doc.go, cache/doc.go, cmd/doc.go, errcode/doc.go, filter/doc.go, provider/doc.go, tag/doc.go, util/doc.go, writer/doc.go
This way we have a more proper documentation showing up on godoc.
Also added the badget link of it.
=> Added: File 'doc.go' to all the packages

provider/resource.go
It'll fix some of the more common diff from terraform apply
Related to #7
=> provider/resource: Add the root default values to the schema

README.md
Short video has been taken to show how terracognita work from beginning
to the terraform plan.
=> README: add short video running terracognita

CHANGELOG.md
Add a simple CHANGELOG.md to fit with the https://keepachangelog.com/en/1.0.0/ spec.
=> Added: CHANGELOG.md to the project

Makefile, README.md
Was outdated and not working correctly so I've updated it with more up to date information.
Also added the `make install` to make it easy to use.
Closes #27
=> Changed: The 'Installation' block of the README

README.md
=> README: Add Gitter badge

.ci/pipeline.yml, .ci/variables.yml, .gitignore, CHANGELOG.md, Makefile
Add our CC pipeline that does:
- Test PRs
- Generate a new release
- Generate docker images
- Generate pre-built binaries.
This PR will solve #31.
=> Add CI/CD pipeline

CHANGELOG.md
Prepare the Changelog for version 0.1.6
=> CHANGELOG: Prepare for 0.1.6

CHANGELOG.md, README.md
Update the format to one we use in other projects
=> Updated: Changelog format

CHANGELOG.md, util/retry.go, util/retry_test.go
Increased the list of possibilities based on AWS SDK directly.
Related to: https://github.com/cycloidio/terracognita/issues/47
=> Changed: Throttle error management

CHANGELOG.md, README.md, google/provider.go, google/reader.go, google/resources.go, google/resourcetype_enumer.go
In this PR I add two more `google` resources.
- google networks 
- google firewalls (fw) (ASG equivalent)
I also fixed a typo in the GCP plugin version. 
It has been tested with `default` resources (network and fw) but also with a custom fw.
=> google networks & google firewalls

CHANGELOG.md, cmd/aws.go, cmd/google.go, cmd/root.go
And also moved the old PreRun functions to the 'Persisnt*' attributes as it's the best place
=> Fix: --region flag to be reusable

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md
add git clone instructions and go dependencies.
Fixes: https://github.com/cycloidio/terracognita/issues/23
=> contributing: initial commit

CHANGELOG.md
* ComputeDisk
* SqlDatabaseInstance
* StorageBucket
=> changelog: add three more google components

README.md, aws/cmd/functions.go
Even transfered some issue to TC and relinked the TODOS we had for it on the code
=> README: Remove last links to 'raws'

CHANGELOG.md
=> CHANGELOG: Bump to version 0.3

CHANGELOG.md, cmd/aws.go, cmd/google.go, cmd/root.go, errcode/codes.go, filter/filter.go, filter/filter_test.go, provider/import.go
Added this new `--target` flag that allows to import specific resources by ID, similar to how TF import works.
Close #80
=> Addeed: New flag '--target'

README.md
removing of old dead links and renaming "platform" to "framework"
=> readme: update cycloid link

.ci/variables.yml
Set project env and customer variables
=> ci: Update variables.yml

README.md
from repology, we can use [badges](https://repology.org/project/terracognita/badges). It can encourage contributions to add support for new package manager (Debian, etc.).
=> add package manager badge

README.md
update the demo with a new one:
* show terracognita import feature
* show result (resources.tf and resources.tfstate)
* terraform plan against Google cloud imported infra
=> readme: update asciicast demo

aws/cmd/template.go, aws/cmd/template_test.go, aws/reader/reader.go
=> Fix: aws pagination error

README.md
add a blogpost link for a high level description of Terracognita
=> readme: add terracognita blogpost ref

CHANGELOG.md, provider/import.go, provider/import_test.go, state/writer.go, state/writer_test.go
dependencies will be based on the interpolation map(https://github.com/cycloidio/terracognita/pull/81) created during the import
=> tfstate: add dependencies

CHANGELOG.md, README.md, cmd/aws.go
And also made it more TF/AWS compatible by adopting the same flags and ENV variables
so if you know how to configure any of the others it'll work by default
Closes #48
=> cmd: Add support for AWS Profile/Config

README.md
Update `curl` command argument from v0.3.0 to v0.5.1
=> Update version in install example

CHANGELOG.md, cmd/root.go, go.mod, go.sum, provider/import.go
Added a log file to always print the output to.
Closes #149
=> Added: Log File

README.md
=> docs: add homebrew install support

CHANGELOG.md
Also added the homebrew support to the changelog
=> CHANGELOG: Prepare for 0.6.0 release

CHANGELOG.md, README.md, cmd/aws.go, cmd/azurerm.go, cmd/google.go, cmd/root.go, go.mod, go.sum, hcl/format.go, hcl/format_test.go, hcl/writer.go, hcl/writer_test.go, provider/resource.go, writer/options.go, writer/options_test.go
Now we can choose to use the `--module` and `--module-variables` to generate modules and specify which attributes do we want to see as variables on the module.
Also with this the files are generated separated for categories so they are easy to read.
Closes #141 
Closes #16
=> Added Modules generation

.ci/pipeline.yml, .ci/variables.yml, Dockerfile, scripts/deploy/aur.sh
in this PR, we add the AUR releasing automation
=> [skip ci] ci: add AUR publishing 

CHANGELOG.md
Basically the PP failed and we have to do another release to fix it
=> CHANGELOG: Explain why the empty release

README.md
So it points to the right community
=> README: Changed the Gitter URL

CHANGELOG.md, tag/tag.go
We had some errors as our validation was light, now we added also the HCL validation which is the one raising
the errors on the examples we found the error
=> tag: Added extra validations for resource names

CHANGELOG.md, go.mod, go.sum, provider/resource.go
Also made the error more readable so we know it's failing because of the docs
Close #199
=> mod: Update 'tfdocs' to have missing resources

README.md
It was lacking a bit so a more specific description has been added
=> README: Update the 'Usage' section

CHANGELOG.md, aws/cmd/functions.go, aws/reader/reader.go, aws/resources.go
Few resources had missing pagination and filter.
Update the aws resources to missing one.
=> aws: update pagination and filter

.ci/variables.yml, Dockerfile, Makefile, README.md, go.mod, go.sum
=> build: bump to use go1.17

CHANGELOG.md, go.mod, go.sum
It fixes an interal bug it has
=> mod: Updated mxwriter to v1.0.4

CHANGELOG.md, azurerm/resources.go
=> azurerm: Fix to enable support for azurerm_resource_group

CHANGELOG.md, go.mod, go.sum, state/writer.go, state/writer_test.go
Now the resources will have the module information on it if it's imported as a module
Closes #240
=> state: Add the module information to the State

CHANGELOG.md, CONTRIBUTING.md, azurerm/cache.go, azurerm/cmd/generate.go, azurerm/cmd/template.go, azurerm/reader_generated.go, azurerm/resources.go, azurerm/resourcetype_enumer.go
=> Azurerm: Added more resources + Added more  templating modularity + Update Contribute.md 

CHANGELOG.md, hcl/writer.go, hcl/writer_test.go
So then it's easy for the user to user the module
Closes #290
=> hcl: Uncomment variables from moduel generation

CHANGELOG.md, CONTRIBUTING.md, google/cache.go, google/cmd/generate.go, google/cmd/template.go, google/provider.go, google/reader.go, google/reader_generated.go, google/reader_irregular_cases.go, google/resources.go, google/resourcetype_enumer.go
=> google: update CONTRIBUTE section, added template modularity and new resources

CHANGELOG.md, cmd/aws.go, cmd/azurerm.go, cmd/google.go, cmd/root.go, cmd/vsphere.go
=> cmd: Added the tags to the helper funcion

CHANGELOG.md, aws/resourcetype_enumer.go, azurerm/resources.go, azurerm/resourcetype_enumer.go, google/resourcetype_enumer.go, mock/provider.go, mock/resource.go, mock/writer.go, vsphere/resourcetype_enumer.go
implement missing azurerm_virtual_machine_data_disk_attachment resource
=> azurerm: implement azurerm_virtual_machine_data_disk_attachment

CHANGELOG.md, hcl/writer.go
It was supposely fixed but actually now, now this fixes it.
Closes #379
=> hcl: Fixed Cyclic relations between different resources
